apiVersion: batch/v1
kind: Job
metadata:
  name: cluster1-job
spec:
  template:
    metadata:
      labels:
        tf-client: "0"
        ts-clustername: cluster1
    spec:
      containers:
      - name: tf-client
        image: elsonrodriguez/tf-dist-test-client-k8s:tensorset-example-0.0
#        command:
#        - sh
#        - -c
#        - while true; do sleep 1; done
        env:
        -  name: TS_CLUSTER_NAME
           value: cluster1
        -  name: TS_CLUSTER_NAMESPACE
           valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 2222
        volumeMounts:
        - name: shared
          mountPath: /shared
      volumes:
      - name: shared
        hostPath:
          path: /shared
      restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: tf-client0
  labels:
    tf-client: "0"
spec:
  type: LoadBalancer
  ports:
  - port: 2222
  selector:
    tf-client: "0"
    ts-clustername: cluster1
---
